open-edge-platform/edge-ai-libraries

libraries/dl-streamer/README.md

Update DLStreamer README about additional sections.

---

sample-applications/chat-question-and-answer-core/chart/templates/pvc.yaml
sample-applications/chat-question-and-answer-core/chart/values.yaml

Update core chart pvc policy

---

sample-applications/chat-question-and-answer/docs/user-guide/deploy-with-edge-orchestrator.md

Here is a PR with fixes to the documentation related to Intel® Open Edge Platform that I found appropriate to introduce as part of `Clean Room Testing`.

[Clean Room] Review of documentation related to Intel® Open Edge Platform

---

.github/CODEOWNERS

[DLStreamer] Extend DLStreamer codeowners list

---

libraries/dl-streamer/README.md

[DLStreamer] Add link to installed packages

---

.github/workflows/publish-docs.yml

Added chatqna-core for documentation publish

---

.github/workflows/publish-docs.yml

Updated input for chatqnacore

---

sample-applications/chat-question-and-answer-core/docs/user-guide/deploy-with-helm.md

Fixed H4 to H3

---

libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.rst
libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu.rst
libraries/dl-streamer/docs/source/get_started/install/uninstall_guide_ubuntu.rst

[DLStreamer] Update install documentation

---

libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu.rst
libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu_wsl2.rst
libraries/dl-streamer/docs/source/get_started/install/uninstall_guide_ubuntu.rst
libraries/dl-streamer/scripts/DLS_install_prerequisites.sh
libraries/dl-streamer/scripts/build_deb_packages.sh
libraries/dl-streamer/scripts/hello_dlstreamer.sh

[DL Streamer] Add help messages to scripts and modify hello_dlstreamer arguments

---

tools/visual-pipeline-and-platform-evaluation-tool/app.py

* Set correct parameters for event handler
* Set log level of httpx to warning
No new dependencies
Tested on Intel Core Ultra 155H system.
Verified that error log from gradio doesn't show up on startup
Verified that httpx info logs don't show up for every request

Suppress error and info logs

---

tools/visual-pipeline-and-platform-evaluation-tool/app.py

Change of model parameter maximum values
No
Tested on 12th Gen Intel(R) Core(TM) i9-12900T with integrated GPU
[ X] I agree to use the APACHE-2.0 license for my code changes.
[ X] I have not introduced any 3rd party components incompatible with APACHE-2.0.
[ X] I have not included any company confidential information, trade secret, password or security token.
[ X] I have performed a self-review of my code.

Change of model parameter intervals

---

README.md

Explicitly list licenses for the Geti and Datumaro components.
NA
NA

update geti and datumaro licenses

---

libraries/dl-streamer/src/monolithic/inference_backend/image_inference/openvino/openvino_image_inference.cpp

[DLStreamer] Update spdlog to v1.15.3

---

libraries/dl-streamer/docs/scripts/all_models.yaml
libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu.rst

[DLStreamer] Fix broken links in documentations

---

sample-applications/chat-question-and-answer-core/chart/templates/_helpers.tpl
sample-applications/chat-question-and-answer-core/chart/templates/deployment.yaml
sample-applications/chat-question-and-answer-core/chart/values.yaml
sample-applications/chat-question-and-answer-core/docs/user-guide/deploy-with-helm.md
sample-applications/chat-question-and-answer-core/docs/user-guide/release-notes.md

Fix helm deployment failure when using default CPU configuration.
Update documentation and previous review comment from previous PR.
N/A

Fix core helm

---

libraries/dl-streamer/src/monolithic/gst/elements/CMakeLists.txt
libraries/dl-streamer/src/monolithic/gst/elements/gvaattachroi/CMakeLists.txt
libraries/dl-streamer/src/monolithic/gst/elements/gvaattachroi/attachroi.cpp
libraries/dl-streamer/src/monolithic/gst/elements/gvaattachroi/attachroi.h
libraries/dl-streamer/src/monolithic/gst/elements/gvaattachroi/gstgvaattachroi.cpp
libraries/dl-streamer/src/monolithic/gst/elements/gvaattachroi/gstgvaattachroi.h
libraries/dl-streamer/src/monolithic/gst/elements/gvaattachroi/register_gvaattachroi.c

[DLStreamer] Added gvaattachroi element

---

sample-applications/chat-question-and-answer-core/chart/Chart.yaml
sample-applications/chat-question-and-answer/chart/Chart.yaml

Update helm chart version to 1.2.0

---

libraries/dl-streamer/samples/gstreamer/README.md

Added missing `install' in README
Fixes 67571
N/A
N/A

[DLStreamer] Fix pip command in readme

---

.github/actions/setup-tools/action.yml
.github/workflows/genai-pre-merge.yaml

[GENAI WORKFLOWS]Genai github actions

---

microservices/document-ingestion/pgvector/main.py

https://github.com/open-edge-platform/edge-ai-libraries/security/code-scanning/21
NA
NA

fix critical security bug

---

microservices/document-ingestion/pgvector/main.py

Fix code scan vulnerability. Full server-side request forgery
Fixes # (NA)
NA

document-ingestion: Fix code scanning vulnerability

---

microservices/document-ingestion/pgvector/config.py
microservices/document-ingestion/pgvector/main.py

Validate URLs parsed in from user when performing url ingestion and ensure they resolve to public ip adresses

document-ingestion: Implement utility to validate URLs

---

.github/workflows/genai-pre-merge.yaml

Branch update

---

.github/CODEOWNERS

Add DL Streamer validation engineers as CODEOWNERS for GitHub Workflows related to DL Streamer. It will help to keep a control over it.

[DLStreamer] Add CODEOWNERS for GitHub workflows related to DLS

---

libraries/dl-streamer/src/monolithic/inference_backend/image_inference/async_with_va_api/va_api_wrapper/vaapi_converter.cpp

[DLStreamer] Apply VA_PROC_PIPELINE_FAST settings for fast scaling mode

---

libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_tensor/paddle_ocr.cpp

[DLSTREAMER] Prevent Paddle OCR errors in special cases

---

libraries/dl-streamer/samples/download_public_models.sh
libraries/dl-streamer/samples/gstreamer/README.md
libraries/dl-streamer/samples/gstreamer/gst_launch/license_plate_recognition/README.md
libraries/dl-streamer/samples/gstreamer/gst_launch/license_plate_recognition/license_plate_recognition.sh

[DLStreamer] Lpr vaapi

---

microservices/time-series-analytics/README.md
microservices/time-series-analytics/docs/user-guide/how-to-deploy-with-helm.md

Fixed link issues in the README.md
Fixes # (issue): NA
NA
Verified the links

microservices/time-series-analytics: Updated README.md

---

libraries/dl-streamer/src/monolithic/inference_backend/image_inference/openvino/openvino_image_inference.cpp

Print out warning message if runtime version used to do model quantization is different than runtime version of inference engine. 
Mismatch may lead to incorrect results. 
No new dependencies. 
Tested with models quantized with an older version of inference engine.

[DLStreamer] Warn users if a model was quantized with different runtime version

---

.github/actions/discover-changed-subfolders/action.yml
.github/actions/setup-tools/action.yml
.github/workflows/genai-pre-merge.yaml

Zizmor scan fix genai

---

microservices/document-ingestion/pgvector/.dockerignore
microservices/document-ingestion/pgvector/docker/Dockerfile

Minor docker image optimization

---

libraries/dl-streamer/samples/gstreamer/gst_launch/geti_deployment/README.md

[DLStreamer] Minor fixes to anomaly-detection sample tutorial

---

tools/visual-pipeline-and-platform-evaluation-tool/pipeline.py
tools/visual-pipeline-and-platform-evaluation-tool/pipelines/smartnvr/config.yaml
tools/visual-pipeline-and-platform-evaluation-tool/pipelines/transportation2/config.yaml
tools/visual-pipeline-and-platform-evaluation-tool/tests/pipeline_test.py

* Add Pipeline Loader
* Add Tests for Pipeline Loader
Fixes ITEP-69388
No new dependencies
By Unit Tests, and local build in Intel Core Ultra 155H

Add Pipeline Loader

---

.github/workflows/genai-pre-merge.yaml

[GENAI] Syntax issues fixed

---

.github/CODEOWNERS

Ownership update for VLM OV serving

---

.github/workflows/timeseries-scans.yml

Added Trivy scans for Timeseries. 
No
No, Testing needs the workflow to be available on Main branch. Will test it separately.

Timeseries Analtyics: Added trivy scans workflow

---

microservices/time-series-analytics/docs/user-guide/how-to-access-api.md
microservices/time-series-analytics/src/opcua_alerts.py

Changes:
1.opcua_alerts.py - Changes to print only the alert message.
2.docs - Added change for alert message format.
No
Sanity tested

time-series-analytics: Print opcua alert message in logs

---

microservices/dlstreamer-pipeline-server/docs/user-guide/release_notes/august-2025.md

updated release notes for august release
your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

updated release notes for august release

---

.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
.github/workflows/dls-build-dev-docker-images.yaml

[SCANS] Enable Trivy image scan for DLStreamer.

---

microservices/time-series-analytics/docs/_static/redirect/index.html
microservices/time-series-analytics/docs/user-guide/Overview.md
microservices/time-series-analytics/docs/user-guide/release_notes/Overview.md
microservices/time-series-analytics/docs/user-guide/release_notes/aug-2025.md

Fixed overview.md headers and added release notes
None
Verified docs

time-series-analytics:  Fix overview.md headers and added release notes

---

microservices/multimodal-embedding-serving/docker/compose.arc-gpu.yaml
microservices/multimodal-embedding-serving/docker/compose.yaml
microservices/vlm-openvino-serving/docker/compose.yaml
microservices/vlm-openvino-serving/setup.sh
sample-applications/video-search-and-summarization/chart/subchart/multimodal-embedding-ms/templates/deployment.yaml
sample-applications/video-search-and-summarization/chart/subchart/vlminference/templates/vlm-inference-deployment.yaml
sample-applications/video-search-and-summarization/docker/compose.search.yaml
sample-applications/video-search-and-summarization/docker/compose.summary.yaml
sample-applications/video-search-and-summarization/docs/user-guide/deploy-with-helm.md
sample-applications/video-search-and-summarization/setup.sh

Remove file mount and use docker external mount for huggingface directory.
Remove file mount and use docker external mount for huggingface directory.

Remove file mount and use docker external mount for huggingface directory

---

microservices/dlstreamer-pipeline-server/Dockerfile

Create resources directories for k8s deployment.
For sample apps using helm deployment, relevant models and files must be copied to the containers. folder paths are required to be present beforehand
None
None
Build and run with helm

[DLStreamer Pipeline Server] Create resources directories for k8s deployment

---

.github/workflows/dlsps-build-scans-pr-workflow.yaml
microservices/dlstreamer-pipeline-server/docker/testfile.txt

Fixed unit test failures and added trivy image scan for extended images.
None
github workflow : https://github.com/open-edge-platform/edge-ai-libraries/actions/runs/15920885931

[DLSPS] Fix for unit test failures on PR job.

---

libraries/dl-streamer/include/dlstreamer/gst/metadata/gva_audio_event_meta.h
libraries/dl-streamer/include/dlstreamer/gst/metadata/gva_json_meta.h
libraries/dl-streamer/include/dlstreamer/gst/metadata/gva_tensor_meta.h
libraries/dl-streamer/include/dlstreamer/gst/metadata/objectdetectionmtdext.h
libraries/dl-streamer/samples/gstreamer/cpp/draw_face_attributes/CMakeLists.txt
libraries/dl-streamer/src/cpu/_gst_plugin/CMakeLists.txt
libraries/dl-streamer/src/gst/elements/CMakeLists.txt
libraries/dl-streamer/src/gst/metadata/gva_audio_event_meta.c
libraries/dl-streamer/src/gst/metadata/gva_json_meta.c
libraries/dl-streamer/src/gst/metadata/gva_tensor_meta.c
libraries/dl-streamer/src/gst/metadata/objectdetectionmtdext.c
libraries/dl-streamer/src/monolithic/gst/elements/gvaattachroi/CMakeLists.txt
libraries/dl-streamer/src/monolithic/gst/elements/gvametapublish/file/gvametapublishfile.hpp
libraries/dl-streamer/src/monolithic/gst/elements/gvametapublish/gvametapublish.hpp
libraries/dl-streamer/src/monolithic/gst/elements/gvapython/CMakeLists.txt
libraries/dl-streamer/src/monolithic/gst/registrator/CMakeLists.txt
libraries/dl-streamer/src/monolithic/gst/registrator/register_elements.cpp
libraries/dl-streamer/src/opencl/_gst_plugin/CMakeLists.txt
libraries/dl-streamer/src/opencv/_gst_plugin/CMakeLists.txt
libraries/dl-streamer/src/opencv/opencv_warp_affine/CMakeLists.txt
libraries/dl-streamer/src/openvino/_gst_plugin/CMakeLists.txt
libraries/dl-streamer/src/vaapi/_gst_plugin/CMakeLists.txt

[DLStreamer] Next portion of the changes to enable compilation on Windows

---

microservices/time-series-analytics/src/classifier_startup.py
microservices/time-series-analytics/src/main.py
microservices/time-series-analytics/tests/.coveragerc
microservices/time-series-analytics/tests/pytest.ini
microservices/time-series-analytics/tests/run_tests.sh
microservices/time-series-analytics/tests/test_classifier_startup.py
microservices/time-series-analytics/tests/test_main.py
microservices/time-series-analytics/tests/test_mr_interface.py
microservices/time-series-analytics/tests/test_opcua_alerts.py

Changes:
tests- Updated the unit tests.

time-series-analytics: Updated the unit tests

---

.github/workflows/timeseries-scans-virus-bandit.yaml

Timeseries: Fixed Virus scan workflow path issue
No
Yes

Timeseries: Fixed Virus scan workflow path issue

---

tools/visual-pipeline-and-platform-evaluation-tool/tests/app_test.py

Fixing:
```
======================================================================
ERROR: test_generate_stream_data (app_test.TestApp.test_generate_stream_data)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/dlstreamer/vippet/tests/app_test.py", line 63, in test_generate_stream_data
stream = generate_stream_data(i)
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/dlstreamer/vippet/app.py", line 445, in generate_stream_data
title = chart_titles[i]
~~~~~~~~~~~~^^^
IndexError: list index out of range
```

[ViPPET] Fix tests

---

.github/CODEOWNERS

[ViPPET] Add pmalatyn do CODEOWNERS

---

.github/workflows/dls-download-models.yaml
libraries/dl-streamer/samples/download_public_models.sh

[DLStreamer] Models downloading workflow - add YOLO INT8 quantized models

---

.github/workflows/timeseries-scans-trivy-image-fs-config.yml
microservices/time-series-analytics/Dockerfile

timeseries: Added CSV report for trivy image scan in workflow
No
Yes

timeseries: Added CSV report for trivy image scan in workflow

---

microservices/time-series-analytics/src/classifier_startup.py

Changes:
src/classifier_startup.py - Fix for bandit vulnerability.
No
Yes, sanity test

time-series-analytics: Fix for bandit

---

libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_tensor/detection_anomaly.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_tensor/detection_anomaly.h

[DLStreamer] Minor refactoring in detection_anomaly converter

---

microservices/time-series-analytics/docs/user-guide/get-started.md
microservices/time-series-analytics/src/main.py

Changes:
src/main.py - Added max payload size 5kB and mandatory keys check in
post config method.
No
Yes, sanity tested

time-series-analytics: Added max payload size for post config

---

libraries/dl-streamer/docker/windows/windows_builder.Dockerfile

[DLStreamer] Fix Windows dockerfile - escape

---

libraries/dl-streamer/docs/source/dev_guide/custom_processing.rst
libraries/dl-streamer/include/dlstreamer/gst/videoanalytics/tensor.h
libraries/dl-streamer/src/monolithic/gst/inference_elements/base/gva_base_inference.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/base/gva_base_inference.h
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/blob_to_meta_converter.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/blob_to_meta_converter.h
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converter_facade.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converter_facade.h
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_roi/blob_to_roi_converter.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_roi/blob_to_roi_converter.h
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_roi/custom_to_roi.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_roi/custom_to_roi.h
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_tensor/blob_to_tensor_converter.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_tensor/blob_to_tensor_converter.h
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_tensor/custom_to_tensor.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_tensor/custom_to_tensor.h
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/post_processor_impl.cpp
libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/post_processor_impl.h

[DLStreamer] Add support for custom post-processing converters

---

microservices/time-series-analytics/tests/test_classifier_startup.py
microservices/time-series-analytics/tests/test_main.py

Changes:
tests - Fixed the unit tests for main.py and classifier_startup.py
No
Yes.

time-series-analytics: Fixed the unit test

---

libraries/dl-streamer/.gitignore
libraries/dl-streamer/Makefile
libraries/dl-streamer/README.md

A set of makefile targets for common development operations on the DLStreamer project.
None
All targets were ran from a `make clean` state to full installation. DLStreamer yolo sample used to validate functionality.

[DLStreamer] Makefile added with common targets

---

libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.rst

[DLStreamer] Add guide for opencv removal

---

libraries/dl-streamer/samples/models_omz_samples.lst
libraries/dl-streamer/tests/unit_tests/check/pipelines/corrupt-data_test/corrupt-data-test.c
libraries/dl-streamer/tests/unit_tests/check/pipelines/frame_drop_test/frame_drop_test.c
libraries/dl-streamer/tests/unit_tests/tests_gstgva/test_pipeline_face_detection_and_emotions-recognition-retail-0003.py

[DLStreamer] Unit tests fixes

---

.github/CODEOWNERS

To unblock code merging.
NA
NA

disable doc review code owners

---

.github/workflows/dlsps-build-scans-pr-workflow.yaml
microservices/dlstreamer-pipeline-server/Dockerfile
microservices/dlstreamer-pipeline-server/README.md
microservices/dlstreamer-pipeline-server/RELEASE_NOTES.md
microservices/dlstreamer-pipeline-server/docker/.env
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-build-from-source.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-run-udf-pipelines.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-use-gpu-for-inference.md
microservices/time-series-analytics/simulator/temperature_input.py

[DL Streamer Pipeline Server] Documentation updates
- Added build for source steps
- Added GPU pipeline tutorials

[DL Streamer Pipeline Server] Documentation updates

---

libraries/dl-streamer/docker/fedora41/fedora41.Dockerfile
libraries/dl-streamer/docker/ubuntu/ubuntu22.Dockerfile
libraries/dl-streamer/docker/ubuntu/ubuntu24.Dockerfile
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.rst

Update docs for fixing error in gstreamer compilation during manual compilation
N/A
N/A

[DLStreamer] Fix gstreamer build error in manual compilation - update docs

---

microservices/time-series-analytics/helm/Chart.yaml

Changed the chart name to include hyphens in the chart name
NA
Yes

Chart.yaml: Changed the name to include hyphens

---

.github/workflows/dls-build-weekly-images.yaml

[DL Streamer Pipeline Server] Push image with latest tag to GHCR

[DL Streamer Pipeline Server] Push image with latest tag to GHCR

---

libraries/dl-streamer/docker/ubuntu/ubuntu22.Dockerfile
libraries/dl-streamer/docker/ubuntu/ubuntu24.Dockerfile
libraries/dl-streamer/scripts/DLS_install_prerequisites.sh

[DLStreamer] Modify NPU drivers installation.

---

libraries/dl-streamer/CMakeLists.txt
libraries/dl-streamer/samples/gstreamer/CMakeLists.txt
libraries/dl-streamer/scripts/build_dlstreamer_dlls.ps1
libraries/dl-streamer/scripts/setup_dls_env.ps1
libraries/dl-streamer/src/monolithic/gst/inference_elements/CMakeLists.txt
libraries/dl-streamer/src/monolithic/gst/registrator/CMakeLists.txt
libraries/dl-streamer/src/monolithic/inference_backend/image_inference/image_inference.cpp
libraries/dl-streamer/vcpkg.json

[DLStreamer] Windows adjustments for CI integration + new build_dlstreamer_dlls.ps1 script

---

libraries/dl-streamer/Makefile
libraries/dl-streamer/docker/fedora41/fedora41.Dockerfile
libraries/dl-streamer/docker/ubuntu/ubuntu22.Dockerfile
libraries/dl-streamer/docker/ubuntu/ubuntu24.Dockerfile
libraries/dl-streamer/docker/windows/windows_builder.Dockerfile
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.rst

[DLStreamer] Update GStreamer and gst-plugins-rs to 1.26.4

---

microservices/time-series-analytics/docs/user-guide/release_notes/aug-2025.md

Added the github hash link to the v1.0.0 
in the release notes
NO
NA

time-series-analytics: Linked the v1.0.0 to the git hash

---

microservices/vlm-openvino-serving/docs/user-guide/get-started.md
sample-applications/video-search-and-summarization/docs/user-guide/build-from-source.md

Update GSG of VLM microservice.

VLM Microservice | Update get-started.md

---

microservices/time-series-analytics/docs/user-guide/how-to-deploy-with-helm.md

Changes:
docs/Update how-to-deploy-with-helm.md - Fixed the kubectl exec command
No
yes

time-series-analytics: docs fix for k8s exec pod command

---

microservices/dlstreamer-pipeline-server/tests/.coveragerc
microservices/dlstreamer-pipeline-server/tests/test_ros2_publisher.py

Unit test warning fixes
- [ x] I agree to use the APACHE-2.0 license for my code changes.
- [ x] I have not introduced any 3rd party components incompatible with APACHE-2.0. 
- [ x] I have not included any company confidential information, trade secret, password or security token. 
- [ x] I have performed a self-review of my code.

[DL Streamer Pipeline Server] Fixing unit test warnings

---

microservices/dlstreamer-pipeline-server/README.md
microservices/dlstreamer-pipeline-server/docker/.env
microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/how-to-advanced/performance/Processing-Latency.md
microservices/dlstreamer-pipeline-server/docs/user-guide/environment-variables.md
microservices/dlstreamer-pipeline-server/docs/user-guide/get-started.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-deploy-with-helm.md
microservices/dlstreamer-pipeline-server/helm/README.md
microservices/dlstreamer-pipeline-server/helm/values.yaml
microservices/dlstreamer-pipeline-server/tests/build.sh
microservices/dlstreamer-pipeline-server/unittests.Dockerfile

[DL Streamer Pipeline Server] Update DLSPS image and miscellaneous improvements
docker compose build && docker compose up
make build && make test

[DL Streamer Pipeline Server] Update DLSPS image and miscellaneous improvements

---

microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/file_ingestion/image_ingestion.md

Document update: Updated multifilesrc image_ingestion pipeline to enable metadata filewrite
https://jira.devtools.intel.com/browse/ITEP-72420 
- [x ] I agree to use the APACHE-2.0 license for my code changes.

[DLStreamer Pipeline Server] Update multifilesrc image_ingestion pipeline to enable metadata filewrite

---

microservices/dlstreamer-pipeline-server/README.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-build-from-source.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-deploy-with-helm.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-publish-metadata-over-ros2.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-run-udf-pipelines.md
microservices/dlstreamer-pipeline-server/helm/README.md

[DL Streamer Pipeline Server] Update helm chart and docs

[DL Streamer Pipeline Server] Update helm chart and docs

---

sample-applications/chat-question-and-answer/chart/templates/nginx-deployment.yaml

Removed the default mode for accessing the conf.

Fix: Permission issue for EMT helm

---

microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-store-s3-frame.md

Added instructions add python dep for s3 tutorial
None
None
NA

[DLStreamer Pipeline Server] docs: Added instructions add python dep for s3 tutorial

---

.github/workflows/dls-download-models.yaml

[DLStreamer] Models downloading workflow - add labels input parameter and fix zizmor findings

---

libraries/dl-streamer/docker/ubuntu/ubuntu22.Dockerfile
libraries/dl-streamer/docker/ubuntu/ubuntu24.Dockerfile

[DLStreamer] Modify Dockerfiles

---

sample-applications/chat-question-and-answer-core/docs/user-guide/build-from-source.md

chatqna-core: Fix misleading documentation

chatqna-core: Fix misleading documentation

---

microservices/dlstreamer-pipeline-server/Dockerfile
microservices/dlstreamer-pipeline-server/docker/.env

[DL Streamer Pipeline Server] Update DLS base image
docker compose build

[DL Streamer Pipeline Server] Update DLS base image

---

tools/visual-pipeline-and-platform-evaluation-tool/Dockerfile.vippet
tools/visual-pipeline-and-platform-evaluation-tool/compose.yml
tools/visual-pipeline-and-platform-evaluation-tool/docs/user-guide/how-to-build-source.md
tools/visual-pipeline-and-platform-evaluation-tool/video_generator/Dockerfile

Use DL Streamer image from docker hub. OS PDT requires it.

chore: use DL Streamer image from docker hub

---

tools/visual-pipeline-and-platform-evaluation-tool/pipelines/simplevs/config.yaml

Replace sample video used in Simple Video Structurization (D-T-C) pipeline. OS PDT requires it.

chore: replace license plate recognition video

---

.github/CODEOWNERS

chore: add ViPPET codeowners

---

sample-applications/video-search-and-summarization/chart/subchart/audio-analyzer/templates/audio-analyzer-models-pvc.yaml

Missing PV condition for persistent

Missing PV condition

---

libraries/dl-streamer/scripts/build_deb_packages.sh

[DLStreamer] Fix shellcheck issues.

---

libraries/dl-streamer/scripts/setup_dls_env.ps1

[DLStreamer] Adjustments of setup_dls_env.ps1 Windows script

---

tools/visual-pipeline-and-platform-evaluation-tool/.gitignore
tools/visual-pipeline-and-platform-evaluation-tool/Dockerfile.vippet
tools/visual-pipeline-and-platform-evaluation-tool/Makefile
tools/visual-pipeline-and-platform-evaluation-tool/app.py
tools/visual-pipeline-and-platform-evaluation-tool/cleanup_models.sh
tools/visual-pipeline-and-platform-evaluation-tool/compose.yml
tools/visual-pipeline-and-platform-evaluation-tool/docs/user-guide/get-started.md
tools/visual-pipeline-and-platform-evaluation-tool/docs/user-guide/how-to-build-source.md
tools/visual-pipeline-and-platform-evaluation-tool/models.sh
tools/visual-pipeline-and-platform-evaluation-tool/pipelines/simplevs/config.yaml
tools/visual-pipeline-and-platform-evaluation-tool/setup_env.sh
tools/visual-pipeline-and-platform-evaluation-tool/utils.py

Cherry-pick of #658
Ask user if public models should be downloaded. OS PDT requires it.
Added 2 make targets:
- **Purpose**: Prompts user to decide whether to download public models during setup
- **Behavior**: 
- Checks if choice was already made (`.public_models_env` file exists)
- If no prior choice, prompts user with "Do you want to download public models? (y/n)"
- Saves the decision as `DOWNLOAD_PUBLIC_MODELS=true/false` in `.public_models_env`
- Skips prompt on subsequent runs to avoid repeated user interaction
- **Integration**: Automatically called as dependency by `run` and `run-dev` targets
- **Purpose**: Clears the previously saved choice to allow re-prompting
- **Behavior**: Removes the `.public_models_env` file
- **Usage**: Run when you want to change your public models …

chore: Ask user if public models should be downloaded

---

libraries/dl-streamer/samples/download_public_models.sh
libraries/dl-streamer/samples/gstreamer/gst_launch/license_plate_recognition/README.md
libraries/dl-streamer/samples/gstreamer/gst_launch/license_plate_recognition/license_plate_recognition.sh

[DLStreamer] Update license plate detection model and LPR sample

---

microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-deploy-with-helm.md

[DL Streamer Pipeline Server] Fix helm chart version
https://jira.devtools.intel.com/browse/ITEP-74083

[DL Streamer Pipeline Server] Fix helm chart version

---

libraries/dl-streamer/docker/ubuntu/ubuntu22.Dockerfile
libraries/dl-streamer/docker/ubuntu/ubuntu24.Dockerfile

[DLStreamer] Add DOCKER_REGISTRY variable to ubuntu Dockerfiles.

---

sample-applications/chat-question-and-answer/deployment-package/chatqna-values-ovms.yaml
sample-applications/chat-question-and-answer/deployment-package/chatqna-values-tgi.yaml
sample-applications/chat-question-and-answer/deployment-package/chatqna-values-vllm.yaml

Updated chatqna deployment Package UI port to aligin with the latest helm chart

Chatqna: EMF Deployment package

---

sample-applications/chat-question-and-answer-core/docs/user-guide/deploy-with-helm.md
sample-applications/chat-question-and-answer/docs/user-guide/deploy-with-helm.md
sample-applications/document-summarization/docs/user-guide/deploy-with-helm.md

Docsum - main - PVC info update

Docsum - main - PVC info update

---

sample-applications/video-search-and-summarization/docs/user-guide/Overview.md
sample-applications/video-search-and-summarization/docs/user-guide/index.rst
sample-applications/video-search-and-summarization/docs/user-guide/overview-architecture.md

Updated the toc and index file to avoid build errors.

updated the tocs and index file to add/remove to avoid build errors

---

libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.rst
libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu.rst
libraries/dl-streamer/scripts/hello_dlstreamer.sh
libraries/dl-streamer/scripts/setup_dls_env.sh

[DLStreamer] Add export GI_TYPELIB_PATH to docs.

---

microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-deploy-with-helm.md

fixed helm tar path
fixed helm tar path
Sanity

[DLStreamer Pipeline Server] docs: fix helm tar path

---

.github/workflows/dls-coverity.yaml

[DLStreamer] Modify Coverity workflow

---

microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/how-to-advanced/get-tensor-vector-data.md
microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/how-to-advanced/https/dlstreamer_pipeline_server_https.md
microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/how-to-advanced/object_tracking/object_tracking.md
microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/how-to-advanced/work-with-other-services.md
microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/publisher/opcua_publish_doc.md
microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/udf/Overview.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-add-system-timestamps-to-metadata.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-change-dlstreamer-pipeline.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-deploy-with-helm.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-use-cpu-for-decode-and-inference.md
microservices/dlstreamer-pipeline-server/docs/user-guide/how-to-use-gpu-for-decode-and-inference.md

docs: fix hyperlinks and minor changes
docs
NA
NA

[DLStreamer Pipeline Server] docs: fix hyperlinks and minor changes

---

sample-applications/video-search-and-summarization/docs/user-guide/get-started.md

Fix incorrect language lexor for Video Search and Summarization.
N/A
Built locally.

Fix incorrect language lexor for Video Search and Summarization.

---

.github/workflows/post-merge.yml
.github/workflows/pre-merge.yml
.github/workflows/publish-docs.yml

Update `orch-ci` workflow to latest to allow matching against branches with `/` characters in branch name
N/A
Tested locally.

Update orch-ci workflow to latest.

---

microservices/dlstreamer-pipeline-server/docs/linkcheck_ignore_append.txt
microservices/dlstreamer-pipeline-server/docs/user-guide/Overview.md
microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/how-to-advanced/work-with-other-services.md

[DL Streamer Pipeline Server] Update doc links pointing to model registry microservice

[DL Streamer Pipeline Server] Update doc links pointing to model registry microservice

---

libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu.md

[DLStreamer] Update docs.

---

libraries/dl-streamer/docs/source/index.md
libraries/dl-streamer/docs/source/release-notes.md

Adding release notes for DL Streamer. Porting #795 

[DOCS] Adding release notes for DL Streamer for main

---

microservices/document-ingestion/pgvector/tests/unit_tests/README.md
microservices/model-registry/docs/user-guide/how-to-build-from-source.md
sample-applications/chat-question-and-answer-core/docs/user-guide/deploy-with-helm.md
sample-applications/chat-question-and-answer-core/docs/user-guide/get-started.md
sample-applications/chat-question-and-answer-core/tests/README.md
sample-applications/chat-question-and-answer/docs/user-guide/deploy-with-helm.md
sample-applications/chat-question-and-answer/docs/user-guide/get-started.md
sample-applications/document-summarization/docs/user-guide/build-from-source.md
sample-applications/document-summarization/docs/user-guide/deploy-with-helm.md
sample-applications/document-summarization/docs/user-guide/get-started.md
sample-applications/document-summarization/tests/unit_tests/README.md
sample-applications/video-search-and-summarization/docs/user-guide/build-from-source.md
sample-applications/video-search-and-summarization/docs/user-guide/deploy-with-helm.md
sample-applications/video-search-and-summarization/docs/user-guide/get-started.md
sample-applications/video-search-and-summarization/pipeline-manager/README.md
sample-applications/video-search-and-summarization/video-ingestion/README.md

Release tag information updated

---

libraries/dl-streamer/docs/source/architecture_2.0/elements_list.md

Fixing duplicate headings in Elements List article. Porting: #798

[DOCS] Fixing elements list for 1.2.0

---

libraries/dl-streamer/docs/source/architecture_2.0/api_ref/index.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_prebuilt.md
libraries/dl-streamer/docs/source/dev_guide/dev_guide_index.md
libraries/dl-streamer/docs/source/dev_guide/how_to_create_model_proc_file.md
libraries/dl-streamer/docs/source/dev_guide/latency_tracer.md
libraries/dl-streamer/docs/source/dev_guide/model_proc_file.md
libraries/dl-streamer/docs/source/dev_guide/python_bindings.md
libraries/dl-streamer/docs/source/dev_guide/yolo_models.md
libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu.md
libraries/dl-streamer/docs/source/get_started/install/install_guide_windows.md
libraries/dl-streamer/docs/source/get_started/install/uninstall_guide_ubuntu.md
libraries/dl-streamer/docs/source/get_started/tutorial.md

Fixing issues in documentation build for DL Streamer. Porting #800 

[DOCS] Fixes for documentation build  for DL Streamer

---

libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.md
libraries/dl-streamer/docs/source/get_started/tutorial.md

Added compilation steps for EMT 3.x OS. Porting #788 

[DOCS] Adding compilation step for EMT - porting #788

---

libraries/dl-streamer/README.md
libraries/dl-streamer/docs/source/index.md

Content review of dl-streamer overview in source/index.md
Fixes # [ITEP-72358](https://jira.devtools.intel.com/browse/ITEP-72358)

[DOCS] dl-streamer overview proofread

---

libraries/dl-streamer/README.md
libraries/dl-streamer/docs/source/index.md

Content review of dl-streamer overview in `source/index.md` and main `README` file. Porting: #808 

[DOCS] Proofreading dlstreamer readme overview for 1.2.0

---

.github/workflows/post-merge.yml
.github/workflows/pre-merge.yml
.github/workflows/publish-docs.yml

Update documentation workflows to match main.
N/A

Update documentation workflows to match main.

---

sample-applications/document-summarization/docs/user-guide/index.rst
sample-applications/video-search-and-summarization/docs/user-guide/Overview.md
sample-applications/video-search-and-summarization/docs/user-guide/get-started.md
sample-applications/video-search-and-summarization/docs/user-guide/index.rst
sample-applications/video-search-and-summarization/docs/user-guide/overview-architecture.md

Sync documentation between main and release-1.2.0 branches.
N/A

Sync documentation between main and release-1.2.0 branches.

---

libraries/dl-streamer/RELEASE_NOTES.md
libraries/dl-streamer/docs/source/elements/elements.md
libraries/dl-streamer/docs/source/elements/gvarealsense.md
libraries/dl-streamer/docs/source/release-notes.md

Updating the release notes and docs for DL Streamer for the 1.2.0 release.

[DOCS] Update dl streamer release notes for 1.2.0

---

libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_build_docker_image.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_prebuilt.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_prerequisites.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_uninstall_guide.md
libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu.md
libraries/dl-streamer/docs/source/get_started/tutorial.md

Proofreading the `advanced installation` section of Developer Guide in Deep Learning Streamer docs.

[DOCS] Proofreading Deep Learning Streamer Dev Guide - pass 1

---

libraries/dl-streamer/RELEASE_NOTES.md
libraries/dl-streamer/docs/source/elements/gvarealsense.md
libraries/dl-streamer/docs/source/release-notes.md

Updating the release notes and docs for DL Streamer for the 1.2.0 release. Porting: #841 

[DOCS] Update dl streamer release notes for main

---

.github/workflows/post-merge.yml
.github/workflows/pre-merge.yml
.github/workflows/publish-docs.yml

Remove obsolete object-store documentation job.
N/A

Remove obsolete object-store documentation job.

---

.github/workflows/dls-download-models.yaml

[DLStreamer] Fix mistake in models downloading workflow - input var

---

tools/visual-pipeline-and-platform-evaluation-tool/pipelines/simplevs/pipeline.py
tools/visual-pipeline-and-platform-evaluation-tool/tests/pipelines_tests/simplevs_tests/pipeline_test.py

This PR  enables support for metadata processing in the SimpleVS pipeline.
Extended existing unit tests and conducted manual integration testing.

[ViPPET] Enable support for metadata processing in the SimpleVS pipeline

---

.github/workflows/GEN-AI-Chat-qna-core.yaml
.github/workflows/GENAI-Audio-analyzer.yaml
.github/workflows/GENAI-Chat-question-and-answer.yaml
.github/workflows/GENAI-Multi-model-emb.yaml
.github/workflows/GENAI-Vdp.yaml
.github/workflows/GENAI-VideoSearchAndSummarization.yaml
.github/workflows/GENAI-doc-ingestion.yaml
.github/workflows/GENAI-docsum.yaml
.github/workflows/GENAI-vlm-openvino-serving.yaml

GENAI-New-worflows

---

libraries/dl-streamer/docs/source/elements/gvaclassify.md
libraries/dl-streamer/docs/source/elements/gvadetect.md
libraries/dl-streamer/docs/source/elements/gvametaconvert.md

Fixing code highlighting issues in `elements` of DL Streamer

[DOCS] Fixing code highlighting issues

---

.github/workflows/dls-download-models.yaml

[DLStreamer] Models downloading workflow - fix github event_name

---

microservices/vector-retriever/milvus/docs/user-guide/get-started.md

Fixing issues with code blocks in docs of the Vector Retriever microservice. Porting: https://github.com/open-edge-platform/edge-ai-libraries/pull/946

[DOCS] Fixing issues in docs for Vector Retriever for main

---

sample-applications/document-summarization/chart/Chart.yaml
sample-applications/document-summarization/chart/subchart/backend/docsum-api/Chart.yaml
sample-applications/document-summarization/chart/subchart/backend/docsum-api/values.yaml
sample-applications/document-summarization/chart/values.yaml
sample-applications/document-summarization/docker-compose.yaml
sample-applications/document-summarization/docs/user-guide/build-from-source.md
sample-applications/document-summarization/docs/user-guide/get-started.md
sample-applications/document-summarization/docs/user-guide/release-notes.md

Update docker image and helmchart version. Also update release notes.

[Document Summary] Update images and helmchart version

---

libraries/edge-control-libraries/plcopen-motion-control/docs/rt-motion/installation_setup/installation/rt_linux.rst

Fixing the issue with duplicate labels in documentation.

[DOCS] Fixing issues in docs for 1.2.0

---

libraries/edge-control-libraries/plcopen-motion-control/docs/index.rst
libraries/edge-control-libraries/plcopen-motion-control/docs/legal.rst
libraries/edge-control-libraries/plcopen-motion-control/docs/rt-motion/installation_setup/installation/rt_linux.rst
libraries/edge-control-libraries/plcopen-motion-control/docs/rt-motion/installation_setup/prerequisites/Apt-Repositories.rst
libraries/edge-control-libraries/plcopen-motion-control/docs/rt-motion/installation_setup/prerequisites/os_setup.rst
libraries/edge-control-libraries/plcopen-motion-control/docs/rt-motion/installation_setup/prerequisites/system_requirement.rst

Updating references in PLCopen Motion Control.

[DOCS] Updating references in PLCopen Motion Control docs for 1.2.0

---

libraries/dl-streamer/docs/source/conf.py

Reformatting the `conf.py` file in DL Streamer docs to fix linter issues. Porting: #969

[DOCS] Reformatting conf.py in DL Streamer docs

---

.github/workflows/pre-merge.yml

Fix exclude_pattern in per-merge workflow.
N/A
N/A

Fix exclude_pattern in pre-merge workflow.

---

.github/workflows/pre-merge.yml

Adjust exclude_pattern to drop leading / character.
N/A
Tested locally.

Adjust exclude_pattern to drop leading / character.

---

libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_build_docker_image.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_prebuilt.md
libraries/dl-streamer/docs/source/dev_guide/coding_style.md

Porting: #993 
Hiding Sphinx directives (tabs) from preview of Markdown files on GitHub

[DOCS] Hiding Sphinx directives from preview of Markdown files for release 1.2.0

---

libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_build_docker_image.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.md
libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_prebuilt.md
libraries/dl-streamer/docs/source/dev_guide/coding_style.md

Hiding Sphinx directives (tabs) from preview of Markdown files on GitHub

[DOCS] Hiding Sphinx directives from preview of Markdown files on GitHub

---

libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu.md
libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu_wsl2.md
libraries/dl-streamer/docs/source/get_started/install/install_guide_windows.md
libraries/dl-streamer/docs/source/get_started/install/uninstall_guide_ubuntu.md
libraries/dl-streamer/docs/source/get_started/tutorial.md

Content review of `Get Started` section of DL Streamer documentation. Porting: #891 

[DOCS] Content review - Get Started section of DL Streamer

---

sample-applications/video-search-and-summarization/docs/user-guide/index.md

Fixing references in the toctree of `index.md`.

[DOCS] Fixing Video Search and Summary toctree

---

microservices/audio-analyzer/docs/toc.rst
microservices/dlstreamer-pipeline-server/docs/toc.rst
microservices/document-ingestion/pgvector/docs/toc.rst
microservices/model-registry/docs/toc.rst
microservices/multimodal-embedding-serving/docs/toc.rst
microservices/time-series-analytics/docs/toc.rst
microservices/vector-retriever/milvus/docs/toc.rst
microservices/visual-data-preparation-for-retrieval/milvus/docs/toc.rst
microservices/visual-data-preparation-for-retrieval/vdms/docs/toc.rst
microservices/vlm-openvino-serving/docs/toc.rst
sample-applications/chat-question-and-answer-core/docs/toc.rst
sample-applications/chat-question-and-answer/docs/toc.rst
sample-applications/document-summarization/docs/toc.rst
sample-applications/video-search-and-summarization/README.md
sample-applications/video-search-and-summarization/docs/toc.rst
tools/visual-pipeline-and-platform-evaluation-tool/docs/toc.rst

Removing redundant files and updating references in documentation. 

[DOCS] Restructuring docs of components in Edge AI Libraries 

---

sample-applications/video-search-and-summarization/README.md
sample-applications/video-search-and-summarization/docs/user-guide/index.md

VSS documentation link fix

---

libraries/dl-streamer/samples/gstreamer/gst_launch/detection_with_yolo/yolo_detect.sh

[DLStreamer] Add precision info to output filename of yolo_detect.sh sample

---

libraries/dl-streamer/src/monolithic/gst/elements/gvametaaggregate/metaaggregate.c

[DLStreamer] Fix DLS building on Windows

---

.github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
.github/workflows/dls-build-and-test-windows.yaml
.github/workflows/dls-build-dev-docker-images-and-run-unit.yaml
.github/workflows/dls-download-models.yaml

[DLStreamer] Temporary comment out of runners reboots
