- .github/workflows/post-merge.yml
- .github/workflows/pre-merge.yml
- .github/workflows/publish-docs.yml
This pull request updates multiple GitHub Actions workflows to enhance permissions management, add support for a new documentation target (`chat-question-and-answer-core`), and improve security by specifying exact workflow versions and secrets. Below is a summary of the most important changes grouped by theme:
* Added granular permissions (`contents: read`, `pull-requests: read`, `issues: write`) to the `.github/workflows/post-merge.yml`, `.github/workflows/pre-merge.yml`, and `.github/workflows/publish-docs.yml` workflows to comply with least privilege principles. [[1]](diffhunk://#diff-649dadd84b5d9938ac7f7a33a4020062fa437edcfc320554adf8bcf62c14602aR14-R18) [[2]](diffhunk://#diff-af56bcb95358063aaf895262efbd18c4c2d3451ae42927d7fe8ae4665e175109R14-R16) …
> Updates permissions, secrets, and pins to action SHA

- tools/visual-pipeline-and-platform-evaluation-tool/Dockerfile.vippet
- tools/visual-pipeline-and-platform-evaluation-tool/app.py
- tools/visual-pipeline-and-platform-evaluation-tool/explore.py
- tools/visual-pipeline-and-platform-evaluation-tool/optimize.py
- tools/visual-pipeline-and-platform-evaluation-tool/pipeline.py
This PR improves the discovery of available elements to use in the pipeline.
Hosts without GPUs don't have the elements that the current pipeline defines.
So now the pipeline will adapt better to the elements available.
This also helps in WSL environments, which has a GPU that DL Streamer don't support
No new dependencies.
Tested in WSL, and Intel Core Ultra 7 155H with multiple profiles, and Arc A770 with GPU profile
> Enable CPU only hosts

- libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.rst
- libraries/dl-streamer/scripts/install_metapublish_dependencies.sh
Build GStreamer version GST 1.26 + remove symbolic links (if present) from previous build of MQTT library. 
None.
Yes, tested manually as part of validation of installation procedure.
> [DLStreamer] Update installation procedure when building from sources.

- libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_roi/blob_to_roi_converter.cpp
Fix memory leak when detection output is augmented with pose/segmentation data.
There was a memory leak when detection output was augmented with auxiliary data (like pose or segmentation). Auxiliary data was not released when detection object itself was removed by NMS algorithm.
Fixes issue reported here: https://github.com/dlstreamer/dlstreamer/issues/461
No new dependencies introduced.
Verified manually the memory leak does not occur for the reported case + automated CI regression validation.
> [DLStreamer] Fix memory leak when detection output is augmented.

- tools/visual-pipeline-and-platform-evaluation-tool/Dockerfile.vippet
- tools/visual-pipeline-and-platform-evaluation-tool/docs/user-guide/how-to-build-source.md
- tools/visual-pipeline-and-platform-evaluation-tool/video_generator/dockerfile
* Use docker.io/intel/dlstreamer:2025.0.1.3-ubuntu24
* Update base image for app and video generator
* Update build docs
Fixes ITEP-67474
The objective of this version bump is to enable [download_public_models.sh]https://github.com/dlstreamer/dlstreamer/blob/master/samples/download_public_models.sh).
The script version in 2025.0.1.2-ubuntu24 has a bug in how ultralytics version is computed.
The one in 2025.0.1.3-ubuntu24 works.
No new dependencies
Please describe the tests that you ran to verify your changes. Provide …
> Bump DL Streamer Version

- microservices/time-series-analytics/src/classifier_startup.py
- microservices/time-series-analytics/src/mr_interface.py
Changes:
1.mr_interface.py- Change to save downloaded model using uuid
2.classifier_startup.py - Change to use uuid for model registry
downloaded model
No.
Yes, tested
> time-series-analytics: Save downloaded model by name uuid

- libraries/dl-streamer/docs/source/elements/gvaclassify.rst
- libraries/dl-streamer/docs/source/elements/gvadetect.rst
- libraries/dl-streamer/docs/source/elements/gvainference.rst
- libraries/dl-streamer/src/monolithic/gst/inference_elements/base/gva_base_inference.cpp
- libraries/dl-streamer/src/monolithic/gst/inference_elements/base/gva_base_inference.h
- libraries/dl-streamer/src/monolithic/gst/inference_elements/base/inference_impl.cpp
- libraries/dl-streamer/src/monolithic/inference_backend/image_inference/async_with_va_api/image_inference_async/image_inference_async.cpp
- libraries/dl-streamer/src/monolithic/inference_backend/image_inference/async_with_va_api/image_inference_async/image_inference_async.h
- libraries/dl-streamer/src/monolithic/inference_backend/image_inference/openvino/openvino_image_inference.cpp
- libraries/dl-streamer/src/monolithic/inference_backend/image_inference/openvino/openvino_image_inference.h
- libraries/dl-streamer/src/monolithic/inference_backend/include/inference_backend/image_inference.h
Add latency scheduling across multiple video streams that share common model instance. In this mode, frames are selected according to their presentation time. 
No new dependencies added. 
Verified with CI system (no regressions), new feature verified with manual tests.
> [DLStreamer] Add option to schedule incoming frames according to their presentation time

- microservices/dlstreamer-pipeline-server/src/manager.py
Fixed an issue where  destination was not being recognized in pipeline server.
The class `GStreamerAppDestination` needs to be loaded in `manager.py` (although unused) before any appsink as destination  based pipeline is launched.
Fixes # (ITEP-70672)
None
- appsink as destination based tests with MQTT, S3 write
> [DLStreamer Pipeline Server] Bugfix: `appsink` based destinations were not being recognized

- libraries/dl-streamer/docs/source/get_started/install/install_guide_ubuntu.rst
- libraries/dl-streamer/samples/gstreamer/gst_launch/detection_with_yolo/README.md
- libraries/dl-streamer/samples/gstreamer/gst_launch/detection_with_yolo/yolo_detect.sh
- libraries/dl-streamer/scripts/hello_dlstreamer.sh
Updated `yolo_detect.sh` and `hello_dlstreamer.sh` to support a new parameter which allows the use to specify the precision of the model they would like to use. Set the default precision to INT8 and default device used to GPU. Implemented a check which will fall back to CPU should a GPU not be available.
Changes manually ran to validate their functionality. Test harness with ground truths has been ran on the `yolo_detect.sh` script to ensure no regression has happened.
> [DLStreamer] Updated samples to support new INT8 models

- microservices/dlstreamer-pipeline-server/src/server/rtsp/gstreamer_rtsp_factory.py
- microservices/dlstreamer-pipeline-server/src/server/webrtc/gstreamer_webrtc_destination.py
- microservices/dlstreamer-pipeline-server/src/server/webrtc/gstreamer_webrtc_manager.py
RTSP and WebRTC pipelines now use GPU specific pipelines based on incoming caps data.
decodebin3 in some machines automatically would convert the memory to VAMemory thereby 
> [DLStreamer Pipeline Server] Enable VA-API based pipelines for RTSP and WebRTC

- .github/CODEOWNERS
Add more granular rules to codeowners, so that the docs team can approve PRs for docs and readme's but at the same time, it does not block component owners from approving and merging PRs with changes to docs. 
Additionally, it organizes the file slightly for better readability and points out two potential issues.
> [DOCS] codeowners extension for docs

- libraries/dl-streamer/src/monolithic/gst/inference_elements/base/inference_impl.cpp
- libraries/dl-streamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_tensor/clip_token_converter.cpp
- libraries/dl-streamer/src/monolithic/inference_backend/image_inference/async_with_va_api/va_api_wrapper/vaapi_converter.cpp
- libraries/dl-streamer/src/monolithic/inference_backend/image_inference/async_with_va_api/va_api_wrapper/vaapi_converter.h
Add support for Clip-ViT-Base-B16/B32 with va-surface-sharing backend
- Added Crop::CENTRAL_RESIZE support in VAAPI converter
- Fixed a missing color space conversion info for OpenVINO preprocessing. OpenVINO preprocessing supports all color formats so the check is not necessary.
- Fixed clip token processor to process both "hidden_state" and "pooler_output".
> [DLStreamer] Add support for Clip-ViT-Base-B16/B32 with va-surface-sharing backend

- .github/workflows/dlsps-build-scans-pr-workflow.yaml
- microservices/dlstreamer-pipeline-server/tests/coverity.sh
Fix for trivy config scan stage in PR workflow.
none
https://github.com/open-edge-platform/edge-ai-libraries/actions/runs/16627174277/job/47046722085
> [DLSPS][CI/CD]added fix for trivy config scan.

- microservices/dlstreamer-pipeline-server/docs/user-guide/environment-variables.md
each env variable
Add explanation for each env variable 
Fixes # https://jira.devtools.intel.com/browse/ITEP-72490 
No new dependency introduced
Checked Visual studio doc preview to verify the changes
> [Manufacturing AI Suite] DLStreamer pipeline server: Add explanation to

- tools/visual-pipeline-and-platform-evaluation-tool/app.py
This pull request fixes a bug in the Visual Pipeline and Platform Evaluation Tool (ViPPET) where the Platform Ceiling Analysis was incorrectly using the live_preview setting from the UI during benchmarking operations.
- Forces `live_preview_enabled` to `False` in the parameter grid for benchmarking to ensure consistent results
> [ViPPET][main] Platform Ceiling Analysis mustn't use live_preview - fix

- tools/visual-pipeline-and-platform-evaluation-tool/Dockerfile.vippet
- tools/visual-pipeline-and-platform-evaluation-tool/compose.yml
- tools/visual-pipeline-and-platform-evaluation-tool/docs/user-guide/how-to-build-source.md
- tools/visual-pipeline-and-platform-evaluation-tool/video_generator/Dockerfile
Use DL Streamer image from docker hub. OS PDT requires it.
Cherry-pick of #672
> chore: use DL Streamer image from docker hub

- microservices/dlstreamer-pipeline-server/src/server/webrtc/gstreamer_webrtc_manager.py
When running WebRTC on platforms that donot have vah264enc gstreamer plugin and the primary pipeline feeds GPU buffers, the secondary pipeline i.e. webrtc pipeline will fail complaining the element is unavailable.
As a workaround, we will fallback to use software encoder (x264enc) instead if the plugin is missing.
https://jira.devtools.intel.com/browse/ITEP-74078
None
sanity tested
CPU pipeline on Core and Xeon(Platinum 8468V)
GPU pipeline on Core and Xeon(Platinum 8468V with dGPU)
```json
{
"config": {
"pipelines": [
{
"name": "pallet_defect_detection",
"source": "gstreamer",
"queue_maxsize": 50,
"pipeline": "{auto_source} name=source ! parsebin ! vah264dec ! vapostproc ! video/x-raw(memory:VAMemory) ! gvadetect device=GPU pre-process-backend=va-surface-sharing …
```
> [DLStreamer Pipeline Server] WebRTC GPU pipeline fallback to software encoding when `vah264enc` is missing

- tools/visual-pipeline-and-platform-evaluation-tool/Dockerfile.vippet
- tools/visual-pipeline-and-platform-evaluation-tool/app.py
- tools/visual-pipeline-and-platform-evaluation-tool/compose.yml
- tools/visual-pipeline-and-platform-evaluation-tool/pipelines/simplevs/config.yaml
- tools/visual-pipeline-and-platform-evaluation-tool/pipelines/simplevs/pipeline.py
- tools/visual-pipeline-and-platform-evaluation-tool/pipelines/smartnvr/pipeline.py
- tools/visual-pipeline-and-platform-evaluation-tool/tests/utils_test.py
- tools/visual-pipeline-and-platform-evaluation-tool/utils.py
- tools/visual-pipeline-and-platform-evaluation-tool/video_generator/Dockerfile
This PR bumps the DLStreamer base image from a release candidate version to a stable release (2025.1.2-ubuntu24) and applies several minor fixes including updating PaddleOCR model precision and adding GPU-specific inference configuration for YOLOv10 models.
- Updates DLStreamer base image from RC version to stable 2025.1.2-ubuntu24
- Changes PaddleOCR model from FP16 to FP32 precision across multiple configuration files
- Adds GPU inference configuration parameter for YOLOv10 models to disable Winograd convolution
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please …
> [ViPPET] Bump DLStreamer to 2025.1.2-ubuntu24 version and apply minor fixes

- tools/visual-pipeline-and-platform-evaluation-tool/collector/Dockerfile
This PR bumps Telegraf to `1.35.3` to address vulnerabilities detected by Trivy.
> [ViPPET] chore: Bump Telegraf to 1.35.3 to address vulnerabilities detected by Trivy

- microservices/document-ingestion/pgvector/docker/Dockerfile
In document ingestion microservice, libgl1-mesa-glx has been obsoleted and not required by chatqna-core application. Remove it to avoid build error.
N/A
> document-ingestion: Remove obsolete package

- libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_compilation.md
- libraries/dl-streamer/docs/source/get_started/tutorial.md
Changes:
1. Added compilation steps for EMT 3.x OS  (tried on the immutable i.e., EMT-D as we need to install packages additionally)
2. Added the note in the tutorial guide which is required  to get the dlstreamer pipeline being rendered
Have verified the tutorial and performance guide DL Streamer tutorials on the EMT OS.
None
Have verified the tutorial and performance guide DL Streamer tutorials on the EMT OS.
> dl-streamer/docs: Added compilation steps for EMT OS

- tools/visual-pipeline-and-platform-evaluation-tool/app.py
- tools/visual-pipeline-and-platform-evaluation-tool/pipelines/simplevs/pipeline.py
- tools/visual-pipeline-and-platform-evaluation-tool/pipelines/smartnvr/pipeline.py
- tools/visual-pipeline-and-platform-evaluation-tool/tests/pipelines_tests/simplevs_tests/pipeline_test.py
- tools/visual-pipeline-and-platform-evaluation-tool/tests/pipelines_tests/smartnvr_tests/pipeline_test.py
- tools/visual-pipeline-and-platform-evaluation-tool/utils.py
This PR adds support for the following tracking types for each pipeline:
-  zero-term        - Zero-term tracker
-  short-term-imageless - Short-term imageless tracker
-  zero-term-imageless - Zero-term imageless tracker
Extended existing unit tests and conducted manual integration testing.
> [ViPPET] Add support for different tracking types

- libraries/edge-control-libraries/fieldbus/ethercat-masterstack/README.md
Fix EtherCAT documentation formatting to enable HTML build.
N/A
N/A
> Fix EtherCAT documentation formatting to enable HTML build.

- libraries/dl-streamer/docs/source/architecture_2.0/architecture_2.0.md
- libraries/dl-streamer/docs/source/dev_guide/advanced_install/advanced_install_guide_index.md
- libraries/dl-streamer/docs/source/dev_guide/dev_guide_index.md
- libraries/dl-streamer/docs/source/dev_guide/how_to_contribute.md
- libraries/dl-streamer/docs/source/dev_guide/model_preparation.md
- libraries/dl-streamer/docs/source/dev_guide/model_proc_file.md
- libraries/dl-streamer/docs/source/elements/elements.md
- libraries/dl-streamer/docs/source/elements/gstelements.md
- libraries/dl-streamer/docs/source/get_started/get_started_index.md
- libraries/dl-streamer/docs/source/get_started/install/install_guide_index.md
- libraries/dl-streamer/docs/source/index.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/Overview.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/camera/Overview.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/camera/genicam.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/configuration/Overview.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/file_ingestion/Overview.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/how-to-advanced/Overview.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/publisher/Overview.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/rest_api/Overview.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/udf/Overview.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/release_notes/Overview.md
- microservices/time-series-analytics/docs/user-guide/release_notes/Overview.md
Toctree RST directives hidden, no longer appear on Github docs preview - port for release-1.2.0
> [DOCS] hide toctrees in markdown files

- libraries/dl-streamer/docs/source/_doxygen/index.md
- microservices/audio-analyzer/docs/user-guide/api-reference.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/camera/basler_doc.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/camera/generic_plugin_doc.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/camera/genicam.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/camera/usb.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/configuration/Overview.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/advanced-guide/detailed_usage/publisher/gvapython_mqtt_publish.md
- microservices/dlstreamer-pipeline-server/docs/user-guide/api-reference.md
- microservices/model-registry/docs/user-guide/api-reference.md
- microservices/model-registry/docs/user-guide/how-to-build-from-source.md
- microservices/multimodal-embedding-serving/docs/user-guide/api-reference.md
- microservices/time-series-analytics/docs/user-guide/api-reference.md
- microservices/visual-data-preparation-for-retrieval/vdms/docs/user-guide/api-reference.md
- microservices/vlm-openvino-serving/docs/user-guide/api-reference.md
- sample-applications/chat-question-and-answer-core/docs/user-guide/api-reference.md
- sample-applications/chat-question-and-answer/docs/user-guide/api-reference.md
- sample-applications/document-summarization/docs/user-guide/api-reference.md
- sample-applications/video-search-and-summarization/docs/user-guide/api-reference.md
Hiding the `eval-rst` and `:orphan:` Sphinx directives from preview of Markdown files.  Porting: #1004 
> [DOCS] Hiding eval-rst and orphan Sphinx directives for release 1.2.0

- .github/workflows/dls-build-and-test-deb_pkgs-and-deb_imgs.yaml
- .github/workflows/dls-build-and-test-windows.yaml
- .github/workflows/dls-build-dev-docker-images-and-run-unit.yaml
- .github/workflows/dls-download-models.yaml
Add restarting/rebooting of self-hosted runners after workflow execution. Reboot is scheduled 15s in advance. This applies to self-hosted runners only.
> [DLStreamer] Add self-hosted runners reboot/restart after workflow execution
